import os
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, KeepTogether
from typing import Dict, Any, List

class PDFReportGenerator:
    """
    Generates a professional PDF analysis report containing ATS score,
    Job Match score, skills assessment, feedback, and career roadmaps.
    """
    
    @staticmethod
    def generate_report(
        candidate_name: str,
        contact_info: Dict[str, str],
        ats_results: Dict[str, Any],
        match_results: Dict[str, Any],
        feedback_results: Dict[str, Any],
        predicted_role: str,
        output_path: str
    ) -> str:
        """
        Creates and saves a styled letter-size PDF report.
        """
        # Ensure target directory exists
        os.makedirs(os.path.dirname(output_path), exist_ok=True)
        
        # Setup document
        doc = SimpleDocTemplate(
            output_path,
            pagesize=letter,
            rightMargin=40,
            leftMargin=40,
            topMargin=40,
            bottomMargin=40
        )
        
        # Setup custom styles
        styles = getSampleStyleSheet()
        
        # Define clean, professional color palette
        c_primary = colors.HexColor("#1E3A8A")  # Deep Navy
        c_secondary = colors.HexColor("#0D9488") # Teal
        c_text = colors.HexColor("#1F2937")      # Dark Grey
        c_light_bg = colors.HexColor("#F3F4F6")  # Light Grey
        
        title_style = ParagraphStyle(
            'DocTitle',
            parent=styles['Heading1'],
            fontName='Helvetica-Bold',
            fontSize=24,
            leading=28,
            textColor=c_primary,
            spaceAfter=6
        )
        
        subtitle_style = ParagraphStyle(
            'DocSubtitle',
            parent=styles['Normal'],
            fontName='Helvetica',
            fontSize=11,
            leading=14,
            textColor=colors.HexColor("#6B7280"),
            spaceAfter=20
        )
        
        h1_style = ParagraphStyle(
            'Heading1_Custom',
            parent=styles['Heading2'],
            fontName='Helvetica-Bold',
            fontSize=14,
            leading=18,
            textColor=c_primary,
            spaceBefore=15,
            spaceAfter=10,
            keepWithNext=True
        )
        
        body_style = ParagraphStyle(
            'Body_Custom',
            parent=styles['Normal'],
            fontName='Helvetica',
            fontSize=10,
            leading=14,
            textColor=c_text
        )
        
        bullet_style = ParagraphStyle(
            'Bullet_Custom',
            parent=body_style,
            leftIndent=15,
            firstLineIndent=-10,
            spaceAfter=5
        )
        
        score_num_style = ParagraphStyle(
            'ScoreNum',
            fontName='Helvetica-Bold',
            fontSize=22,
            leading=26,
            alignment=1, # Center
            textColor=c_secondary
        )
        
        score_lbl_style = ParagraphStyle(
            'ScoreLbl',
            fontName='Helvetica-Bold',
            fontSize=10,
            leading=12,
            alignment=1, # Center
            textColor=c_text
        )
        
        story = []
        
        # 1. Header Section
        story.append(Paragraph("AI-Powered Resume Analysis Report", title_style))
        story.append(Paragraph("Generated by AI Resume Match & Analytics System", subtitle_style))
        
        # 2. Candidate & Target Job Meta Table
        contact_items = []
        if contact_info.get('email'):
            contact_items.append(f"<b>Email:</b> {contact_info['email']}")
        if contact_info.get('phone'):
            contact_items.append(f"<b>Phone:</b> {contact_info['phone']}")
        if contact_info.get('linkedin'):
            contact_items.append(f"<b>LinkedIn:</b> linkedin.com/in/...")
        if contact_info.get('github'):
            contact_items.append(f"<b>GitHub:</b> github.com/...")
            
        contact_str = "  |  ".join(contact_items)
        
        meta_data = [
            [Paragraph(f"<b>Candidate Name:</b> {candidate_name}", body_style), 
             Paragraph(f"<b>Predicted Role:</b> {predicted_role}", body_style)],
            [Paragraph(contact_str if contact_str else "<b>Contact details:</b> Extracted partially", body_style), ""]
        ]
        
        meta_table = Table(meta_data, colWidths=[320, 210])
        meta_table.setStyle(TableStyle([
            ('SPAN', (0, 1), (1, 1)),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
            ('TOPPADDING', (0, 0), (-1, -1), 4),
            ('BACKGROUND', (0, 0), (-1, -1), c_light_bg),
            ('INNERGRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#E5E7EB")),
            ('BOX', (0, 0), (-1, -1), 1, colors.HexColor("#D1D5DB")),
        ]))
        story.append(meta_table)
        story.append(Spacer(1, 15))
        
        # 3. Score Summary Table (ATS Gauge & JD Match equivalents)
        score_data = [
            [
                Paragraph(f"{ats_results['overall_score']}/100", score_num_style),
                Paragraph(f"{match_results['match_score']}%", score_num_style),
                Paragraph(f"{predicted_role}", ParagraphStyle('PredRole', fontName='Helvetica-Bold', fontSize=12, leading=14, alignment=1, textColor=c_primary))
            ],
            [
                Paragraph("Overall ATS Score", score_lbl_style),
                Paragraph("Job Match Score", score_lbl_style),
                Paragraph("Classification Role", score_lbl_style)
            ]
        ]
        score_table = Table(score_data, colWidths=[175, 175, 180])
        score_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor("#F0FDFA")),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('BOX', (0, 0), (-1, -1), 1, colors.HexColor("#99F6E4")),
            ('TOPPADDING', (0, 0), (-1, 0), 10),
            ('BOTTOMPADDING', (0, 1), (-1, 1), 10),
            ('LINEAFTER', (0, 0), (0, 1), 1, colors.HexColor("#CCFBF1")),
            ('LINEAFTER', (1, 0), (1, 1), 1, colors.HexColor("#CCFBF1")),
        ]))
        story.append(score_table)
        story.append(Spacer(1, 15))
        
        # 4. Resume Strengths & Weaknesses
        story.append(Paragraph("Resume Evaluation (Heuristics Analysis)", h1_style))
        
        strengths_content = []
        for s in feedback_results.get('strengths', []):
            strengths_content.append(Paragraph(f"• {s}", bullet_style))
        
        weaknesses_content = []
        for w in feedback_results.get('weaknesses', []):
            weaknesses_content.append(Paragraph(f"• {w}", bullet_style))
            
        eval_data = [
            [Paragraph("<b>Key Strengths</b>", ParagraphStyle('GreenL', fontName='Helvetica-Bold', fontSize=11, textColor=colors.HexColor("#065F46"))),
             Paragraph("<b>Areas for Improvement</b>", ParagraphStyle('RedL', fontName='Helvetica-Bold', fontSize=11, textColor=colors.HexColor("#991B1B")))],
            [strengths_content, weaknesses_content]
        ]
        eval_table = Table(eval_data, colWidths=[265, 265])
        eval_table.setStyle(TableStyle([
            ('VALIGN', (0, 0), (-1, -1), 'TOP'),
            ('BACKGROUND', (0, 0), (0, 0), colors.HexColor("#ECFDF5")),
            ('BACKGROUND', (1, 0), (1, 0), colors.HexColor("#FEF2F2")),
            ('BOX', (0, 0), (0, 1), 1, colors.HexColor("#A7F3D0")),
            ('BOX', (1, 0), (1, 1), 1, colors.HexColor("#FCA5A5")),
            ('TOPPADDING', (0, 0), (-1, -1), 8),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
            ('LEFTPADDING', (0, 0), (-1, -1), 8),
            ('RIGHTPADDING', (0, 0), (-1, -1), 8),
        ]))
        story.append(KeepTogether([eval_table]))
        story.append(Spacer(1, 15))
        
        # 5. Skills Analysis
        story.append(Paragraph("Skills Assessment", h1_style))
        
        matching_skills_str = ", ".join(match_results.get('matching_skills', []))
        missing_skills_str = ", ".join(match_results.get('missing_skills', []))
        
        if not matching_skills_str:
            matching_skills_str = "None identified in common with the Job Description."
        if not missing_skills_str:
            missing_skills_str = "No key skills from Job Description missing! Exceptional match."
            
        skills_data = [
            [Paragraph("<b>Matching Skills:</b>", ParagraphStyle('BoldText', fontName='Helvetica-Bold', fontSize=10, textColor=c_secondary)),
             Paragraph(matching_skills_str, body_style)],
            [Paragraph("<b>Missing Skills (Gaps):</b>", ParagraphStyle('BoldText2', fontName='Helvetica-Bold', fontSize=10, textColor=colors.HexColor("#DC2626"))),
             Paragraph(missing_skills_str, body_style)]
        ]
        
        skills_table = Table(skills_data, colWidths=[130, 400])
        skills_table.setStyle(TableStyle([
            ('VALIGN', (0, 0), (-1, -1), 'TOP'),
            ('LINEBELOW', (0, 0), (-1, 0), 0.5, colors.HexColor("#E5E7EB")),
            ('TOPPADDING', (0, 0), (-1, -1), 6),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ]))
        story.append(KeepTogether([skills_table]))
        story.append(Spacer(1, 15))
        
        # 6. Career Suggestions & Next Steps
        story.append(Paragraph("Tailored Recommendations", h1_style))
        
        recs_elements = []
        
        # Projects Suggestion
        recs_elements.append(Paragraph("<b>Recommended Hands-on Projects:</b>", ParagraphStyle('SubTitleBold', fontName='Helvetica-Bold', fontSize=11, textColor=c_primary, spaceBefore=4, spaceAfter=4)))
        for proj in feedback_results.get('project_suggestions', []):
            recs_elements.append(Paragraph(f"• {proj}", bullet_style))
            
        recs_elements.append(Spacer(1, 8))
        
        # Certifications Suggestion
        recs_elements.append(Paragraph("<b>Recommended Industry Certifications:</b>", ParagraphStyle('SubTitleBold2', fontName='Helvetica-Bold', fontSize=11, textColor=c_primary, spaceBefore=4, spaceAfter=4)))
        for cert in feedback_results.get('certification_suggestions', []):
            recs_elements.append(Paragraph(f"• {cert}", bullet_style))
            
        # Roadmap
        recs_elements.append(Spacer(1, 8))
        recs_elements.append(Paragraph("<b>Structured Learning Roadmap:</b>", ParagraphStyle('SubTitleBold3', fontName='Helvetica-Bold', fontSize=11, textColor=c_primary, spaceBefore=4, spaceAfter=4)))
        for idx, step in enumerate(feedback_results.get('learning_roadmap', []), 1):
            recs_elements.append(Paragraph(f"<b>Step {idx}:</b> {step}", bullet_style))
            
        story.append(KeepTogether(recs_elements))
        
        # Build PDF
        doc.build(story)
        return output_path
